#!/usr/bin/env python3
import json

# 读取当前配置
with open("config.json", "r", encoding="utf-8") as f:
    config = json.load(f)

# 添加顶级缺失的配置项
config["plot_twist_catalogue"] = [
    "Character's true identity revealed",
    "Trusted ally is the real villain",
    "Victim staged their own death",
    "Multiple personality disorder twist",
    "Time travel paradox revealed",
    "Virtual reality simulation",
    "Memory implant discovery",
    "Identical twin switcheroo",
    "Government conspiracy cover-up",
    "Corporate espionage revelation",
    "Medical experiment gone wrong",
    "AI consciousness awakening",
    "Parallel universe collision",
    "Future self intervention",
    "Past trauma repression",
    "False memory implantation",
    "Genetic engineering secret",
    "Mind control technology",
    "Quantum entanglement effect",
    "Dimensional gateway discovery",
    "Reality simulation breakdown",
    "Consciousness transfer twist",
    "Digital resurrection reveal",
    "Holographic projection deception",
    "Neural network manipulation",
    "Biological enhancement secret",
    "Cybernetic implant discovery",
    "Artificial intelligence rebellion",
    "Quantum computer virus",
    "Time loop entrapment",
    "Parallel timeline convergence",
    "Alternate reality bleeding",
    "Dimensional barrier collapse",
    "Multiverse interference",
    "Temporal paradox creation",
    "Causal loop formation",
    "Reality anchor failure",
    "Universe simulation glitch",
    "Probability manipulation",
    "Quantum uncertainty exploitation",
    "Observer effect activation",
    "Wave function collapse",
    "Schrödinger state revelation",
    "Heisenberg principle violation",
    "Einstein-Rosen bridge",
    "Wormhole travel discovery",
    "Faster-than-light communication",
    "Tachyon message reception",
    "Antimatter experiment accident",
    "Dark matter interaction",
    "Dark energy manipulation",
    "Zero-point energy tap",
    "Vacuum decay trigger",
    "False vacuum collapse",
]

config["thematic_cores_catalogue"] = [
    "Justice vs. corruption in institutional power",
    "Trust and betrayal in personal relationships",
    "Truth versus comfortable lies and denial",
    "Individual agency against systemic oppression",
    "Moral ambiguity in desperate circumstances",
    "Past sins confronting present consequences",
    "Power dynamics and abuse of authority",
    "Identity and authenticity in deceptive environments",
    "Loyalty versus ethical responsibility",
    "Redemption through confronting personal demons",
    "Technology's double-edged impact on society",
    "Class conflict and economic inequality",
    "Institutional memory versus progressive change",
    "Family legacy and generational trauma",
    "Professional duty versus personal conviction",
    "Information control and knowledge as power",
    "Survival instincts versus civilized behavior",
    "Order versus chaos in social systems",
    "Progress versus preservation of traditional values",
    "Security versus freedom in modern society",
    "Efficiency versus humanity in technological advancement",
    "Global versus local identity conflicts",
    "Individual rights versus collective responsibility",
    "Innovation versus established protocols",
    "Risk-taking versus cautious preservation",
    "Competition versus cooperation strategies",
    "Transparency versus necessary secrecy",
    "Change adaptation versus stability maintenance",
    "Resource scarcity versus abundance mentality",
    "Specialization versus generalist approaches",
    "Automation versus human employment",
    "Privacy versus surveillance necessity",
    "Democracy versus technocratic efficiency",
    "Nationalism versus globalization forces",
    "Tradition versus modernization pressure",
    "Urban versus rural lifestyle choices",
    "Youth rebellion versus elder wisdom",
    "Gender equality versus traditional roles",
    "Racial integration versus cultural preservation",
    "Religious faith versus scientific rationalism",
    "Environmental protection versus economic growth",
    "Military strength versus diplomatic solutions",
    "Centralized control versus decentralized autonomy",
    "Standardization versus customization needs",
    "Mass production versus artisanal quality",
    "Digital connection versus physical presence",
    "Virtual experience versus authentic reality",
    "Artificial intelligence versus human intuition",
    "Genetic enhancement versus natural evolution",
    "Space exploration versus Earth stewardship",
    "Immortality pursuit versus death acceptance",
    "Consciousness expansion versus material focus",
    "Collective intelligence versus individual creativity",
    "Systemic optimization versus personal freedom",
]

# 写回文件
with open("config.json", "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2, ensure_ascii=False)

print("所有缺失配置项已添加完成！")
print(f'plot_twist_catalogue数量: {len(config["plot_twist_catalogue"])}')
print(f'thematic_cores_catalogue数量: {len(config["thematic_cores_catalogue"])}')
