#!/usr/bin/env python3
import json

# 读取当前配置
with open("config.json", "r", encoding="utf-8") as f:
    config = json.load(f)

# 添加所有剩余的additional_story_elements配置项
additional_elements = {
    "protagonist_psychological_states": [
        "Haunted by past failure",
        "Driven by need for justice",
        "Struggling with moral ambiguity",
        "Obsessed with truth",
        "Paralyzed by analysis",
        "Motivated by protection",
        "Corrupted by power",
        "Inspired by idealism",
        "Hardened by experience",
        "Softened by compassion",
        "Sharpened by training",
        "Dulled by routine",
        "Energized by challenge",
        "Exhausted by pressure",
        "Focused by urgency",
        "Scattered by overwhelm",
        "Calmed by procedure",
        "Agitated by chaos",
        "Confident in abilities",
        "Doubtful of methods",
        "Certain of purpose",
        "Confused by complexity",
        "Simplified by clarity",
        "Complicated by nuance",
        "Strengthened by support",
        "Weakened by isolation",
        "Empowered by knowledge",
        "Diminished by ignorance",
        "Elevated by success",
        "Humbled by failure",
        "Encouraged by progress",
        "Discouraged by setbacks",
        "Motivated by recognition",
        "Demotivated by criticism",
        "Inspired by mentorship",
        "Betrayed by colleagues",
        "Supported by family",
        "Abandoned by friends",
        "Trusted by superiors",
        "Suspected by subordinates",
        "Respected by peers",
        "Feared by enemies",
        "Loved by community",
        "Hated by criminals",
        "Admired by public",
        "Scorned by media",
        "Praised by authorities",
        "Criticized by activists",
        "Understood by therapist",
        "Misunderstood by everyone",
        "Connected to purpose",
        "Disconnected from feelings",
        "Aligned with values",
        "Conflicted by choices",
    ],
    "protagonist_backstory_secrets": [
        "Former military intelligence",
        "Witness protection survivor",
        "Corrupt cop turned honest",
        "Academic fraud coverup",
        "Medical malpractice incident",
        "Financial crime involvement",
        "Family tragedy guilt",
        "Addiction recovery",
        "Mental health struggles",
        "Relationship betrayal",
        "Career sabotage",
        "Identity theft victim",
        "Government experiment subject",
        "Corporate whistleblower",
        "Religious cult survivor",
        "Organized crime witness",
        "International espionage",
        "War crime observer",
        "Environmental disaster survivor",
        "Medical experiment volunteer",
        "Genetic testing subject",
        "Psychological study participant",
        "Social media manipulation target",
        "Information warfare victim",
        "Surveillance state refugee",
        "AI algorithm trainer",
        "Neural network test subject",
        "Quantum computer operator",
        "Time travel experiment participant",
        "Parallel universe visitor",
        "Dimensional gateway traveler",
        "Reality simulation escapee",
        "Virtual world refugee",
        "Digital consciousness backup",
        "Memory implant recipient",
        "Emotion regulation subject",
        "Behavior modification target",
        "Personality restructuring survivor",
        "Identity reconstruction patient",
        "Trauma memory deletion",
        "False memory implantation",
        "Recovered memory therapy",
        "Hypnotic suggestion subject",
        "Subliminal programming target",
        "Psychological conditioning survivor",
        "Behavioral economics test",
        "Social psychology experiment",
        "Cognitive bias study",
        "Decision-making research",
        "Risk assessment analysis",
        "Probability calculation study",
        "Game theory experiment",
        "Strategic thinking test",
        "Problem-solving evaluation",
    ],
    "antagonist_protagonist_connections": [
        "Former partner",
        "Childhood friend",
        "Family member",
        "Ex-lover",
        "College roommate",
        "Military unit member",
        "Work colleague",
        "Neighbor",
        "Mentor figure",
        "Student relationship",
        "Therapy patient",
        "Doctor-patient",
        "Lawyer-client",
        "Teacher-student",
        "Coach-athlete",
        "Employer-employee",
        "Landlord-tenant",
        "Creditor-debtor",
        "Business partner",
        "Investment advisor",
        "Insurance agent",
        "Financial planner",
        "Real estate agent",
        "Contractor",
        "Service provider",
        "Consultant",
        "Therapist",
        "Counselor",
        "Social worker",
        "Case manager",
        "Probation officer",
        "Parole officer",
        "Court reporter",
        "Legal secretary",
        "Paralegal",
        "Court clerk",
        "Bailiff",
        "Security guard",
        "Investigator",
        "Detective",
        "Federal agent",
        "Intelligence officer",
        "Military officer",
        "Government official",
        "Corporate executive",
        "Board member",
        "Shareholder",
        "Investor",
        "Competitor",
        "Rival",
        "Enemy",
        "Adversary",
        "Opposing counsel",
        "Prosecution witness",
        "Defense witness",
        "Expert witness",
        "Character witness",
        "Alibi provider",
        "Co-conspirator",
        "Accomplice",
    ],
    "antagonist_signature_traits": [
        "Always wears expensive watches",
        "Collects antique weapons",
        "Speaks multiple languages",
        "Has photographic memory",
        "Never forgets a slight",
        "Obsessed with punctuality",
        "Immaculate personal grooming",
        "Distinctive cologne scent",
        "Unique laugh pattern",
        "Specific hand gestures",
        "Characteristic walking gait",
        "Memorable voice timber",
        "Unusual eye color",
        "Distinctive scar pattern",
        "Specific clothing style",
        "Particular food preferences",
        "Unique drinking habits",
        "Special smoking ritual",
        "Characteristic nervous tics",
        "Specific sleep patterns",
        "Unique exercise routine",
        "Particular reading habits",
        "Special music preferences",
        "Distinctive artwork taste",
        "Unique collecting hobby",
        "Specific travel patterns",
        "Particular technology use",
        "Characteristic communication style",
        "Unique decision-making process",
        "Special problem-solving approach",
        "Distinctive leadership style",
        "Particular negotiation tactics",
        "Unique persuasion methods",
        "Characteristic manipulation techniques",
        "Special intimidation strategies",
        "Distinctive reward systems",
        "Particular punishment methods",
        "Unique loyalty requirements",
        "Special trust conditions",
        "Characteristic secrecy levels",
        "Distinctive information sharing",
        "Particular delegation style",
        "Unique quality standards",
        "Special perfectionism traits",
        "Distinctive attention details",
        "Characteristic patience levels",
        "Particular urgency responses",
        "Unique priority systems",
        "Special flexibility degrees",
        "Distinctive adaptation methods",
        "Characteristic resilience patterns",
        "Particular stress responses",
        "Unique recovery strategies",
        "Special motivation sources",
    ],
    "supporting_character_expertise": [
        "Computer forensics",
        "Financial analysis",
        "Legal research",
        "Medical examination",
        "Psychological profiling",
        "Surveillance techniques",
        "Database investigation",
        "Network security",
        "Cryptography",
        "Language translation",
        "Cultural consultation",
        "Historical research",
        "Archaeological analysis",
        "Scientific testing",
        "Laboratory procedures",
        "Field investigation",
        "Interview techniques",
        "Interrogation methods",
        "Evidence preservation",
        "Crime scene analysis",
        "Ballistics examination",
        "DNA testing",
        "Fingerprint analysis",
        "Handwriting analysis",
        "Voice recognition",
        "Facial recognition",
        "Body language reading",
        "Lie detection",
        "Risk assessment",
        "Threat analysis",
        "Security planning",
        "Protection protocols",
        "Emergency response",
        "Crisis management",
        "Negotiation tactics",
        "Conflict resolution",
        "Strategic planning",
        "Tactical execution",
        "Operations coordination",
        "Resource management",
        "Budget analysis",
        "Project management",
        "Quality control",
        "Performance evaluation",
        "Training development",
        "Education planning",
        "Curriculum design",
        "Skill assessment",
        "Competency evaluation",
        "Certification processes",
        "Accreditation standards",
        "Compliance monitoring",
        "Audit procedures",
        "Inspection protocols",
        "Review processes",
        "Validation methods",
    ],
    "supporting_character_reliability": [
        "Completely trustworthy",
        "Generally reliable",
        "Situationally dependable",
        "Conditionally helpful",
        "Reluctantly cooperative",
        "Occasionally useful",
        "Unpredictably available",
        "Marginally competent",
        "Barely adequate",
        "Questionably loyal",
        "Potentially compromised",
        "Likely unreliable",
        "Probably dishonest",
        "Certainly corrupt",
        "Definitely dangerous",
        "Absolutely treacherous",
        "Loyal to the end",
        "Faithful under pressure",
        "Steady in crisis",
        "Calm under fire",
        "Cool under pressure",
        "Reliable in emergency",
        "Dependable in chaos",
        "Stable in uncertainty",
        "Consistent in performance",
        "Predictable in behavior",
        "Regular in attendance",
        "Punctual in delivery",
        "Accurate in reporting",
        "Precise in execution",
        "Thorough in investigation",
        "Complete in analysis",
        "Detailed in documentation",
        "Comprehensive in coverage",
        "Extensive in research",
        "Intensive in study",
        "Focused in attention",
        "Concentrated in effort",
        "Dedicated in service",
        "Committed to mission",
        "Devoted to cause",
        "Passionate about justice",
        "Driven by purpose",
        "Motivated by principle",
        "Inspired by idealism",
        "Guided by ethics",
        "Governed by morality",
        "Bound by honor",
        "Constrained by duty",
        "Limited by protocol",
        "Restricted by regulation",
        "Controlled by procedure",
        "Directed by policy",
        "Managed by oversight",
        "Supervised by authority",
        "Monitored by leadership",
    ],
    "supporting_character_hidden_agendas": [
        "Secret romantic interest",
        "Hidden financial motive",
        "Undisclosed family connection",
        "Concealed political loyalty",
        "Suppressed criminal past",
        "Masked professional rivalry",
        "Hidden personal vendetta",
        "Secret organizational allegiance",
        "Undisclosed medical condition",
        "Concealed addiction problem",
        "Suppressed trauma history",
        "Masked psychological disorder",
        "Hidden identity crisis",
        "Secret double life",
        "Undisclosed foreign connection",
        "Concealed intelligence background",
        "Suppressed military service",
        "Masked academic fraud",
        "Hidden research misconduct",
        "Secret patent theft",
        "Undisclosed trade secret",
        "Concealed industrial espionage",
        "Suppressed corporate corruption",
        "Masked financial fraud",
        "Hidden insurance scam",
        "Secret real estate conspiracy",
        "Undisclosed tax evasion",
        "Concealed money laundering",
        "Suppressed asset hiding",
        "Masked bankruptcy fraud",
        "Hidden credit manipulation",
        "Secret investment scam",
        "Undisclosed Ponzi scheme",
        "Concealed pyramid operation",
        "Suppressed charity fraud",
        "Masked foundation corruption",
        "Hidden government contract",
        "Secret public fund access",
        "Undisclosed lobby connection",
        "Concealed campaign finance",
        "Suppressed election interference",
        "Masked voter suppression",
        "Hidden information warfare",
        "Secret propaganda campaign",
        "Undisclosed social media manipulation",
        "Concealed digital identity theft",
        "Suppressed blockchain hacking",
        "Masked cryptocurrency theft",
        "Hidden AI surveillance",
        "Secret neural manipulation",
        "Undisclosed memory alteration",
        "Concealed consciousness transfer",
        "Suppressed quantum interference",
        "Masked dimensional travel",
        "Hidden time manipulation",
        "Secret reality editing",
    ],
}

# 合并到现有的additional_story_elements中
config["additional_story_elements"].update(additional_elements)

# 写回文件
with open("config.json", "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2, ensure_ascii=False)

print("配置文件完整更新完成！")
for key, value in additional_elements.items():
    print(f"{key}数量: {len(value)}")
print(f'总additional_story_elements项目数: {len(config["additional_story_elements"])}')
