#!/usr/bin/env python3
import json

# 读取当前配置
with open("config.json", "r", encoding="utf-8") as f:
    config = json.load(f)

# 添加剩余的additional_story_elements配置项
remaining_elements = {
    "inciting_incidents": [
        "Mysterious disappearance",
        "Unexplained death",
        "Data breach discovery",
        "Whistleblower revelation",
        "Corporate scandal exposure",
        "Government document leak",
        "Financial irregularity found",
        "Security breach detected",
        "Identity theft reported",
        "Fraud scheme uncovered",
        "Conspiracy evidence found",
        "Corruption allegation made",
        "Blackmail attempt received",
        "Threat message delivered",
        "Surveillance footage discovered",
        "Witness testimony given",
        "Expert analysis completed",
        "Laboratory results returned",
        "Background check revealed",
        "Audit findings published",
        "Investigation request filed",
        "Complaint formally lodged",
        "Lawsuit officially filed",
        "Criminal charges brought",
        "Search warrant executed",
        "Arrest warrant issued",
        "Subpoena legally served",
        "Court order enforced",
        "Emergency declared",
        "Alert system activated",
        "Protocol breach occurred",
        "Security failure happened",
        "System malfunction detected",
        "Network intrusion found",
        "Data corruption discovered",
        "Backup failure occurred",
        "Recovery process failed",
        "Restoration attempt blocked",
        "Access denial encountered",
        "Permission revocation imposed",
        "Clearance suspension ordered",
        "Authorization withdrawal demanded",
        "Credential invalidation required",
        "Certification revocation mandated",
        "License suspension imposed",
        "Registration cancellation ordered",
        "Membership termination declared",
        "Contract cancellation announced",
        "Agreement violation discovered",
        "Terms breach identified",
        "Condition failure detected",
        "Requirement non-compliance found",
    ],
    "red_herrings": [
        "Suspicious financial transaction",
        "Misleading witness statement",
        "Planted evidence discovery",
        "False alibi provided",
        "Doctored surveillance footage",
        "Fabricated document trail",
        "Staged crime scene",
        "Manipulated digital evidence",
        "Coached witness testimony",
        "Bribed official statement",
        "Corrupted database entry",
        "Altered forensic sample",
        "Modified laboratory result",
        "Falsified expert opinion",
        "Manufactured physical evidence",
        "Simulated digital footprint",
        "Artificial communication record",
        "Synthetic audio recording",
        "Computer-generated video",
        "Deepfake media content",
        "Holographic projection",
        "Virtual reality simulation",
        "Augmented reality overlay",
        "Mixed reality presentation",
        "Digital twin model",
        "AI-generated content",
        "Machine learning prediction",
        "Algorithm manipulation result",
        "Quantum calculation error",
        "Probability miscalculation",
        "Statistical manipulation",
        "Mathematical model flaw",
        "Analytical bias introduction",
        "Research methodology error",
        "Data collection mistake",
        "Sample contamination",
        "Control group compromise",
        "Variable manipulation",
        "Result interpretation error",
        "Conclusion bias",
        "Report selective editing",
        "Study limitation hiding",
        "Conflict of interest concealment",
        "Funding source obscuring",
        "Methodology detail omission",
        "Data point exclusion",
        "Outlier result hiding",
        "Pattern recognition failure",
        "Correlation causation confusion",
        "Temporal sequence error",
        "Spatial relationship mistake",
        "Causal inference flaw",
    ],
    "resolution_types": [
        "Justice served legally",
        "Truth publicly exposed",
        "Conspiracy dismantled",
        "Corruption eliminated",
        "System reformed",
        "Policy changed",
        "Procedure improved",
        "Protocol updated",
        "Training enhanced",
        "Education expanded",
        "Awareness raised",
        "Understanding deepened",
        "Knowledge shared",
        "Information disseminated",
        "Evidence preserved",
        "Documentation secured",
        "Testimony recorded",
        "Statement verified",
        "Account confirmed",
        "Story validated",
        "Version corroborated",
        "Narrative supported",
        "Explanation accepted",
        "Theory proven",
        "Hypothesis confirmed",
        "Prediction verified",
        "Model validated",
        "Simulation accurate",
        "Calculation correct",
        "Analysis sound",
        "Conclusion justified",
        "Recommendation implemented",
        "Solution deployed",
        "Fix applied",
        "Patch installed",
        "Update completed",
        "Upgrade finished",
        "Enhancement added",
        "Feature implemented",
        "Function activated",
        "Service restored",
        "Operation resumed",
        "Process restarted",
        "System rebooted",
        "Network reconnected",
        "Database synchronized",
        "Backup restored",
        "Recovery completed",
        "Restoration finished",
        "Reconstruction done",
        "Rebuilding accomplished",
        "Renewal achieved",
    ],
    "primary_locations": [
        "Metropolitan police headquarters",
        "Federal investigation bureau",
        "Corporate security office",
        "Government intelligence agency",
        "Private investigation firm",
        "Legal defense office",
        "District attorney building",
        "Courthouse complex",
        "Prison facility",
        "Detention center",
        "Witness protection safe house",
        "Security company headquarters",
        "Technology corporation campus",
        "Pharmaceutical research lab",
        "Financial services building",
        "Insurance company office",
        "Real estate development firm",
        "Construction company site",
        "Manufacturing plant facility",
        "Transportation hub terminal",
        "Communication center building",
        "Media organization headquarters",
        "Broadcasting station complex",
        "Publishing house office",
        "Educational institution campus",
        "Research university facility",
        "Medical center complex",
        "Hospital system network",
        "Healthcare organization building",
        "Rehabilitation center facility",
        "Mental health clinic",
        "Addiction treatment center",
        "Social services office",
        "Community center building",
        "Religious organization facility",
        "Cultural institution building",
        "Museum complex",
        "Library system network",
        "Archive storage facility",
        "Information center building",
        "Data processing center",
        "Computer server farm",
        "Network operations center",
        "Cybersecurity command center",
        "Digital forensics laboratory",
        "Evidence processing facility",
        "Crime scene investigation unit",
        "Ballistics testing lab",
        "DNA analysis laboratory",
        "Fingerprint processing center",
        "Voice recognition facility",
        "Facial recognition center",
        "Surveillance monitoring station",
        "Communication intercept facility",
        "Intelligence analysis center",
        "Strategic planning office",
    ],
    "secondary_locations": [
        "Airport security checkpoint",
        "Train station platform",
        "Bus terminal waiting area",
        "Subway system tunnel",
        "Highway rest stop",
        "Gas station convenience store",
        "Shopping mall food court",
        "Department store parking garage",
        "Restaurant kitchen",
        "Bar back alley",
        "Hotel lobby",
        "Motel room",
        "Apartment building stairwell",
        "Office building elevator",
        "Parking structure rooftop",
        "Construction site trailer",
        "Warehouse loading dock",
        "Factory assembly line",
        "Laboratory storage room",
        "Hospital emergency room",
        "School gymnasium",
        "University lecture hall",
        "Library reading room",
        "Museum exhibition space",
        "Theater backstage area",
        "Stadium concession stand",
        "Arena locker room",
        "Park maintenance shed",
        "Beach lifeguard station",
        "Marina boat slip",
        "Lighthouse observation deck",
        "Bridge toll booth",
        "Tunnel maintenance access",
        "Sewer system junction",
        "Utility company substation",
        "Power plant control room",
        "Water treatment facility",
        "Waste management center",
        "Recycling processing plant",
        "Environmental testing site",
        "Weather monitoring station",
        "Communication relay tower",
        "Satellite uplink facility",
        "Radio transmission site",
        "Television broadcast center",
        "Internet service provider",
        "Cable company headquarters",
        "Telephone switching station",
        "Data storage warehouse",
        "Cloud computing center",
        "Artificial intelligence lab",
        "Robotics research facility",
        "Biotechnology laboratory",
        "Genetic engineering center",
        "Pharmaceutical testing site",
        "Medical device factory",
    ],
    "time_periods": [
        "Early morning hours (3-6 AM)",
        "Dawn breaking (6-8 AM)",
        "Morning rush (8-10 AM)",
        "Late morning (10 AM-12 PM)",
        "Lunch period (12-2 PM)",
        "Afternoon shift (2-5 PM)",
        "Evening commute (5-7 PM)",
        "Dinner hours (7-9 PM)",
        "Night time (9 PM-12 AM)",
        "Late night (12-3 AM)",
        "Weekend morning",
        "Weekend afternoon",
        "Weekend evening",
        "Weekend late night",
        "Holiday period",
        "Vacation season",
        "School year",
        "Summer break",
        "Winter holiday",
        "Spring semester",
        "Fall semester",
        "Academic year",
        "Fiscal year",
        "Calendar year",
        "Business quarter",
        "Monthly cycle",
        "Weekly schedule",
        "Daily routine",
        "Hourly intervals",
        "Minute-by-minute",
        "Second-by-second",
        "Real-time monitoring",
        "Historical period",
        "Contemporary era",
        "Future timeline",
        "Alternative timeline",
        "Parallel universe",
        "Quantum reality",
        "Simulated environment",
        "Virtual world",
        "Digital realm",
        "Cyber space",
        "Network domain",
        "Database timeline",
        "System clock",
        "Server time",
        "Greenwich mean time",
        "Universal coordinated time",
        "Local time zone",
        "Daylight saving time",
        "Standard time",
        "Military time",
        "International time",
        "Global schedule",
        "Worldwide coordination",
        "Universal timing",
    ],
    "environmental_pressures": [
        "Extreme weather conditions",
        "Natural disaster threat",
        "Environmental contamination",
        "Air quality crisis",
        "Water shortage emergency",
        "Power grid failure",
        "Communication blackout",
        "Transportation shutdown",
        "Supply chain disruption",
        "Economic market crash",
        "Political system collapse",
        "Social unrest outbreak",
        "Civil disorder escalation",
        "Emergency declaration",
        "Martial law imposition",
        "Curfew enforcement",
        "Quarantine establishment",
        "Isolation protocol",
        "Containment procedure",
        "Evacuation order",
        "Shelter-in-place directive",
        "Emergency broadcast",
        "Alert system activation",
        "Warning signal",
        "Danger notification",
        "Threat assessment",
        "Risk evaluation",
        "Hazard identification",
        "Safety protocol activation",
        "Security measure implementation",
        "Protection procedure deployment",
        "Defense system engagement",
        "Countermeasure activation",
        "Response plan execution",
        "Recovery operation",
        "Restoration process",
        "Rebuilding effort",
        "Reconstruction project",
        "Renewal initiative",
        "Reform movement",
        "Change management",
        "Transition planning",
        "Transformation process",
        "Evolution cycle",
        "Development phase",
        "Growth period",
        "Expansion stage",
        "Contraction phase",
        "Consolidation period",
        "Stabilization effort",
        "Optimization process",
        "Efficiency improvement",
        "Performance enhancement",
        "Quality upgrade",
        "Standard elevation",
        "Benchmark achievement",
    ],
    "clue_discovery_methods": [
        "Surveillance footage analysis",
        "Digital forensics examination",
        "Database cross-referencing",
        "Communication intercept",
        "Financial transaction tracking",
        "Travel pattern analysis",
        "Social network mapping",
        "Behavioral pattern recognition",
        "Language analysis",
        "Voice recognition",
        "Facial recognition",
        "Biometric identification",
        "DNA comparison",
        "Fingerprint matching",
        "Handwriting analysis",
        "Document examination",
        "Physical evidence testing",
        "Chemical analysis",
        "Ballistics examination",
        "Tool mark comparison",
        "Tire impression analysis",
        "Footprint examination",
        "Blood spatter analysis",
        "Fiber comparison",
        "Paint chip analysis",
        "Glass fragment examination",
        "Soil sample comparison",
        "Pollen analysis",
        "Electronic device examination",
        "Computer hard drive analysis",
        "Mobile phone data extraction",
        "GPS tracking review",
        "Internet history analysis",
        "Email examination",
        "Social media investigation",
        "Cloud storage access",
        "Network traffic analysis",
        "Metadata examination",
        "Timestamp verification",
        "Location data correlation",
        "Witness interview",
        "Expert consultation",
        "Informant information",
        "Undercover operation",
        "Surveillance operation",
        "Stakeout mission",
        "Infiltration assignment",
        "Reconnaissance activity",
        "Intelligence gathering",
        "Information collection",
        "Data mining",
        "Pattern analysis",
        "Trend identification",
        "Anomaly detection",
        "Outlier recognition",
        "Correlation discovery",
    ],
    "evidence_types": [
        "Physical documents",
        "Digital files",
        "Audio recordings",
        "Video footage",
        "Photograph evidence",
        "Financial records",
        "Communication logs",
        "Travel documents",
        "Identity verification",
        "Biometric data",
        "DNA samples",
        "Fingerprint evidence",
        "Handwriting samples",
        "Voice recordings",
        "Security camera footage",
        "Surveillance photos",
        "Transaction records",
        "Bank statements",
        "Credit card bills",
        "Receipt collections",
        "Contract documents",
        "Agreement papers",
        "Legal filings",
        "Court records",
        "Government documents",
        "Official reports",
        "Investigation files",
        "Case studies",
        "Research papers",
        "Academic records",
        "Educational transcripts",
        "Professional certifications",
        "Employment records",
        "Personnel files",
        "Background checks",
        "Reference letters",
        "Medical records",
        "Health reports",
        "Treatment history",
        "Prescription records",
        "Insurance claims",
        "Policy documents",
        "Coverage records",
        "Claim history",
        "Property records",
        "Real estate documents",
        "Ownership papers",
        "Transfer records",
        "Vehicle registration",
        "Driver license records",
        "Traffic violation history",
        "Accident reports",
        "Communication evidence",
        "Phone records",
        "Email archives",
        "Text message logs",
        "Social media posts",
        "Internet browsing history",
        "Search query logs",
        "Download records",
    ],
    "revelation_triggers": [
        "Witness comes forward",
        "New evidence discovered",
        "Expert analysis completed",
        "Database match found",
        "Pattern recognition algorithm",
        "Correlation analysis result",
        "Timeline reconstruction",
        "Location triangulation",
        "Communication intercept",
        "Surveillance breakthrough",
        "Undercover intelligence",
        "Informant information",
        "Confession obtained",
        "Plea bargain negotiated",
        "Immunity deal struck",
        "Cooperation agreement",
        "Whistleblower protection",
        "Anonymous tip received",
        "Public disclosure",
        "Media investigation",
        "Journalistic inquiry",
        "Freedom of information request",
        "Legal discovery process",
        "Court order enforcement",
        "Search warrant execution",
        "Arrest warrant service",
        "Subpoena compliance",
        "Testimony compelled",
        "Expert witness testimony",
        "Character witness statement",
        "Alibi verification",
        "Timeline confirmation",
        "Location verification",
        "Identity confirmation",
        "Relationship proof",
        "Motive establishment",
        "Opportunity demonstration",
        "Method explanation",
        "Means identification",
        "Access proof",
        "Knowledge demonstration",
        "Skill verification",
        "Capability confirmation",
        "Resource identification",
        "Connection establishment",
        "Network mapping",
        "Organization chart",
        "Hierarchy identification",
        "Command structure",
        "Decision chain",
        "Authority verification",
        "Responsibility assignment",
        "Accountability establishment",
        "Liability determination",
        "Fault identification",
        "Error acknowledgment",
    ],
}

# 合并到现有的additional_story_elements中
config["additional_story_elements"].update(remaining_elements)

# 写回文件
with open("config.json", "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2, ensure_ascii=False)

print("最终配置文件更新完成！")
for key, value in remaining_elements.items():
    print(f"{key}数量: {len(value)}")
print(f'总additional_story_elements项目数: {len(config["additional_story_elements"])}')
