#!/usr/bin/env python3
import json

# 读取当前配置
with open("config.json", "r", encoding="utf-8") as f:
    config = json.load(f)

# 添加additional_story_elements配置
config["additional_story_elements"] = {
    "tone_options": [
        "Dark and brooding",
        "Suspenseful and tense",
        "Psychological and unsettling",
        "Fast-paced and action-packed",
        "Slow-burn and methodical",
        "Gritty and realistic",
        "Paranoid and conspiratorial",
        "Cold and clinical",
        "Intense and dramatic",
        "Atmospheric and moody",
        "Cerebral and intellectual",
        "Visceral and brutal",
        "Elegant and sophisticated",
        "Raw and emotional",
        "Technical and procedural",
        "International and exotic",
        "Urban and street-smart",
        "Corporate and sleek",
        "Military and tactical",
        "Scientific and analytical",
        "Legal and bureaucratic",
        "Medical and clinical",
        "Academic and scholarly",
        "Journalistic and investigative",
        "Political and Machiavellian",
        "Religious and spiritual",
        "Cultural and ethnic",
        "Historical and period-appropriate",
        "Futuristic and cutting-edge",
        "Nostalgic and retrospective",
        "Cynical and world-weary",
        "Idealistic and principled",
        "Pragmatic and realistic",
        "Philosophical and existential",
        "Technological and digital",
        "Environmental and organic",
        "Social and communal",
        "Individual and personal",
        "Collective and societal",
        "Global and international",
        "Local and community-based",
        "Regional and geographical",
        "Temporal and time-focused",
        "Spatial and location-based",
        "Dimensional and reality-bending",
        "Quantum and probability-based",
        "Mathematical and logical",
        "Emotional and heart-driven",
        "Intuitive and instinctive",
        "Rational and evidence-based",
        "Spiritual and transcendent",
        "Material and physical",
        "Abstract and conceptual",
    ],
    "atmosphere_options": [
        "Claustrophobic tension",
        "Open paranoia",
        "Creeping dread",
        "Explosive action",
        "Methodical investigation",
        "Psychological pressure",
        "Corporate intrigue",
        "Street-level grit",
        "High-tech surveillance",
        "International espionage",
        "Military precision",
        "Academic inquiry",
        "Medical urgency",
        "Legal maneuvering",
        "Journalistic pursuit",
        "Political manipulation",
        "Religious fervor",
        "Cultural conflict",
        "Historical mystery",
        "Futuristic uncertainty",
        "Nostalgic melancholy",
        "Cynical detachment",
        "Idealistic passion",
        "Pragmatic efficiency",
        "Philosophical contemplation",
        "Technological innovation",
        "Environmental harmony",
        "Social cooperation",
        "Individual determination",
        "Collective action",
        "Global perspective",
        "Local intimacy",
        "Regional pride",
        "Temporal displacement",
        "Spatial disorientation",
        "Dimensional confusion",
        "Quantum uncertainty",
        "Mathematical precision",
        "Emotional intensity",
        "Intuitive insight",
        "Rational analysis",
        "Spiritual transcendence",
        "Material abundance",
        "Abstract complexity",
        "Concrete simplicity",
        "Dynamic movement",
        "Static contemplation",
        "Rhythmic pulsing",
        "Harmonic resonance",
        "Discordant chaos",
        "Melodic flow",
        "Percussive impact",
        "Sustained tension",
        "Sudden release",
    ],
    "core_concept_hooks": [
        "Identity theft gone wrong",
        "Memory manipulation conspiracy",
        "AI surveillance state",
        "Genetic engineering coverup",
        "Quantum computer virus",
        "Neural implant hacking",
        "Time travel paradox",
        "Parallel universe collision",
        "Corporate espionage",
        "Government conspiracy",
        "Medical experiment",
        "Archaeological discovery",
        "Environmental disaster",
        "Religious extremism",
        "Cultural appropriation",
        "Academic fraud",
        "Sports corruption",
        "Media manipulation",
        "Financial fraud",
        "Insurance scam",
        "Real estate conspiracy",
        "Educational corruption",
        "Healthcare fraud",
        "Research misconduct",
        "Patent theft",
        "Trade secret stealing",
        "Industrial espionage",
        "Economic sabotage",
        "Market manipulation",
        "Currency counterfeiting",
        "Cryptocurrency theft",
        "Blockchain hacking",
        "Digital identity theft",
        "Social media manipulation",
        "Information warfare",
        "Propaganda campaign",
        "Election interference",
        "Voter suppression",
        "Campaign finance violation",
        "Lobby corruption",
        "Government contract fraud",
        "Public fund embezzlement",
        "Tax evasion scheme",
        "Money laundering operation",
        "Asset hiding conspiracy",
        "Bankruptcy fraud",
        "Credit fraud network",
        "Investment scam",
        "Ponzi scheme operation",
        "Pyramid scheme network",
        "Multi-level marketing fraud",
        "Charity fraud scandal",
        "Non-profit corruption",
        "Foundation mismanagement",
    ],
    "central_mystery_questions": [
        "Who can be trusted?",
        "What really happened that night?",
        "Why are they lying?",
        "Where is the missing evidence?",
        "When did the deception begin?",
        "How deep does this go?",
        "What are they hiding?",
        "Who is pulling the strings?",
        "Why now?",
        "What's the real motive?",
        "Who benefits from this?",
        "What's the endgame?",
        "How many people are involved?",
        "What triggered this sequence?",
        "Where did it all start?",
        "Who knew what when?",
        "What's the connection?",
        "Why this victim?",
        "How did they know?",
        "What's missing from the story?",
        "Who's telling the truth?",
        "What's the real timeline?",
        "How did they access this?",
        "Why this location?",
        "What's the significance of the date?",
        "Who had the means?",
        "What's the pattern?",
        "How did they disappear?",
        "Why leave this evidence?",
        "What's the message?",
        "Who's next on the list?",
        "What's the countdown for?",
        "How do we stop this?",
        "What's the trigger event?",
        "Who's the real target?",
        "What's the ultimate goal?",
        "How long has this been planned?",
        "What's the escape route?",
        "Who's the inside person?",
        "What's the backup plan?",
        "How do they communicate?",
        "What's the code mean?",
        "Where's the safe house?",
        "Who's the contact?",
        "What's the signal?",
        "How do they know our moves?",
        "What's our weak point?",
        "Who can we trust?",
        "What's our next step?",
        "How do we expose this?",
        "What's our proof?",
        "Who will believe us?",
        "What's our leverage?",
        "How do we survive this?",
    ],
}

# 写回文件
with open("config.json", "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2, ensure_ascii=False)

print("配置文件已更新完成！")
print("tone_options数量:", len(config["additional_story_elements"]["tone_options"]))
print(
    "atmosphere_options数量:",
    len(config["additional_story_elements"]["atmosphere_options"]),
)
print(
    "core_concept_hooks数量:",
    len(config["additional_story_elements"]["core_concept_hooks"]),
)
print(
    "central_mystery_questions数量:",
    len(config["additional_story_elements"]["central_mystery_questions"]),
)
