#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成扩展版恐怖小说配置文件
每个类别扩展到50个选项，具备诺贝尔文学奖级别的深度和丰富性
"""

import json
import os


def create_extended_config():
    """创建扩展配置文件"""

    config = {
        "story_settings": {
            "target_audio_length_minutes": [
                [90, 120],
                [120, 150],
                [150, 180],
                [180, 240],
            ],
            "primary_horror_subgenres": [
                "Supernatural Horror",
                "Psychological Horror",
                "Gothic Horror",
                "Cosmic Horror",
                "Serial Killer/Thriller",
                "Folk Horror",
                "Body Horror",
                "Sci-Fi Horror",
                "Zombie/Apocalyptic Horror",
                "Existential Horror",
                "Eco-Horror",
                "Techno-Horror",
                "Medical Horror",
                "Religious Horror",
                "Occult Horror",
                "Primordial Horror",
                "Temporal Horror",
                "Dimensional Horror",
                "Quantum Horror",
                "Viral Horror",
                "Neural Horror",
                "Genetic Horror",
                "Metamorphic Horror",
                "Void Horror",
                "Ancestral Horror",
                "Societal Horror",
                "Institutional Horror",
                "Environmental Horror",
                "Archaeological Horror",
                "Linguistic Horror",
                "Mathematical Horror",
                "Philosophical Horror",
                "Metaphysical Horror",
                "Archetypal Horror",
                "Alchemical Horror",
                "Anthropological Horror",
                "Evolutionary Horror",
                "Consciousness Horror",
                "Information Horror",
                "Probability Horror",
                "Resonance Horror",
                "Fractal Horror",
                "Entropy Horror",
                "Memory Horror",
                "Identity Horror",
                "Reality Horror",
                "Perception Horror",
                "Sensory Horror",
                "Cognitive Horror",
                "Systematic Horror",
            ],
            "secondary_horror_elements": [
                "Paranormal Investigation",
                "Religious/Occult Themes",
                "Family Curse",
                "Isolation/Claustrophobia",
                "Medical/Scientific Horror",
                "Historical Horror",
                "Urban Legend",
                "Possession/Exorcism",
                "Time Loop/Temporal Horror",
                "Dimensional Horror",
                "Plague/Infection",
                "Technology Gone Wrong",
                "Nature Horror",
                "Dream/Nightmare Horror",
                "Amnesia/Lost Memory",
                "Generational Trauma",
                "Collective Unconscious",
                "Forbidden Knowledge",
                "Ancient Prophecies",
                "Quantum Entanglement",
                "Parallel Realities",
                "Subliminal Programming",
                "Genetic Engineering",
                "Artificial Intelligence",
                "Virtual Reality Traps",
                "Bioengineering",
                "Nanotechnology",
                "Climate Catastrophe",
                "Social Media Manipulation",
                "Corporate Conspiracy",
                "Government Experiments",
                "Archaeological Discovery",
                "Extinct Species Revival",
                "Neural Implants",
                "Memory Manipulation",
                "Consciousness Transfer",
                "Digital Ghosts",
                "Holographic Reality",
                "Psychoactive Substances",
                "Sleep Deprivation",
                "Sensory Overload",
                "Information Warfare",
                "Cultural Appropriation",
                "Language Evolution",
                "Mathematical Paradox",
                "Philosophical Crisis",
                "Existential Doubt",
                "Moral Relativism",
                "Truth Fragmentation",
                "Reality Consensus",
            ],
            "horror_atmospheres": [
                "Creeping Dread",
                "Sudden Terror",
                "Overwhelming Despair",
                "Paranoid Anxiety",
                "Primal Fear",
                "Existential Horror",
                "Visceral Disgust",
                "Psychological Unease",
                "Supernatural Menace",
                "Cosmic Insignificance",
                "Temporal Vertigo",
                "Reality Dissolution",
                "Identity Fragmentation",
                "Sensory Deprivation",
                "Cognitive Dissonance",
                "Metaphysical Confusion",
                "Evolutionary Anxiety",
                "Technological Alienation",
                "Social Isolation",
                "Cultural Displacement",
                "Linguistic Barrier",
                "Mathematical Incomprehension",
                "Scientific Uncertainty",
                "Philosophical Doubt",
                "Moral Ambiguity",
                "Ethical Collapse",
                "Spiritual Vacuum",
                "Ancestral Guilt",
                "Collective Shame",
                "Generational Fear",
                "Hereditary Madness",
                "Bloodline Corruption",
                "DNA Memory",
                "Cellular Horror",
                "Quantum Uncertainty",
                "Probability Nightmare",
                "Information Overload",
                "Data Corruption",
                "System Failure",
                "Network Terror",
                "Digital Haunting",
                "Virtual Possession",
                "Artificial Consciousness",
                "Machine Learning Horror",
                "Algorithm Malfunction",
                "Code Mutation",
                "Binary Nightmares",
                "Pixel Degradation",
                "Signal Interference",
                "Frequency Distortion",
            ],
            "settings_locations": [
                "Abandoned Mental Asylum",
                "Isolated Mountain Cabin",
                "Old Victorian Mansion",
                "Underground Tunnels/Catacombs",
                "Remote Fishing Village",
                "Decaying Urban Hospital",
                "Ancient Forest/Woods",
                "Desolate Farmhouse",
                "Crumbling Church/Cathedral",
                "Fog-Shrouded Small Town",
                "Coastal Lighthouse",
                "Desert Research Facility",
                "Underground Bunker",
                "Haunted University Campus",
                "Abandoned Theme Park",
                "Decommissioned Space Station",
                "Arctic Research Outpost",
                "Deep Ocean Laboratory",
                "Quantum Physics Institute",
                "Genetic Engineering Facility",
                "Neural Network Data Center",
                "Abandoned Space Colony",
                "Underwater Archaeological Site",
                "Ancient Monastery",
                "Prehistoric Cave System",
                "Radioactive Exclusion Zone",
                "Abandoned Mining Town",
                "Floating City Platform",
                "Underground Subway System",
                "Derelict Cruise Ship",
                "Isolated Weather Station",
                "Forgotten Library Archive",
                "Ruined Observatory",
                "Abandoned Film Studio",
                "Decaying Shopping Mall",
                "Empty Office Complex",
                "Deserted Military Base",
                "Haunted Boarding School",
                "Remote Lighthouse Station",
                "Abandoned Amusement Park",
                "Decrepit Opera House",
                "Forgotten Cemetery",
                "Ancient Burial Ground",
                "Mystical Stone Circle",
                "Hidden Underground City",
                "Floating Laboratory",
                "Orbital Research Station",
                "Interdimensional Gateway",
                "Time Displacement Chamber",
                "Reality Simulation Facility",
            ],
            "time_periods": [
                "Modern Day (2020s)",
                "Late 20th Century (1980s-1990s)",
                "Mid 20th Century (1950s-1960s)",
                "Early 20th Century (1900s-1930s)",
                "Victorian Era (1800s)",
                "Medieval Times",
                "Near Future (2030s-2040s)",
                "Renaissance Period (1400s-1600s)",
                "Industrial Revolution (1760s-1840s)",
                "Roaring Twenties (1920s)",
                "Great Depression Era (1930s)",
                "World War Era (1940s)",
                "Cold War Period (1950s-1980s)",
                "Digital Age Dawn (1990s)",
                "Millennium Turn (2000s)",
                "Post-Internet Era (2010s)",
                "Climate Change Era (2020s-2030s)",
                "Post-Pandemic World (2025-2035)",
                "AI Revolution Period (2030s-2040s)",
                "Space Colonization Era (2040s-2050s)",
                "Genetic Enhancement Age (2050s-2060s)",
                "Neural Interface Era (2060s-2070s)",
                "Consciousness Upload Age (2070s-2080s)",
                "Post-Human Period (2080s-2100s)",
                "Multiverse Discovery Era (22nd Century)",
                "Ancient Mesopotamia (3000 BCE)",
                "Egyptian Dynasty Period (2600-2100 BCE)",
                "Classical Antiquity (800 BCE-500 CE)",
                "Dark Ages (500-1000 CE)",
                "Crusades Period (1095-1291 CE)",
                "Black Death Era (1347-1351 CE)",
                "Witch Trial Period (1450-1750 CE)",
                "Age of Exploration (1400s-1600s)",
                "Enlightenment Era (1685-1815)",
                "Napoleonic Wars (1803-1815)",
                "American Civil War (1861-1865)",
                "Belle Époque (1871-1914)",
                "Spanish Flu Pandemic (1918-1920)",
                "Prohibition Era (1920-1933)",
                "Nuclear Age Dawn (1945-1960)",
                "Space Race Period (1955-1975)",
                "Counterculture Era (1960s-1970s)",
                "Personal Computer Revolution (1970s-1980s)",
                "Chernobyl Aftermath (1986-1990s)",
                "Berlin Wall Fall (1989-1991)",
                "Internet Birth (1990s)",
                "Y2K Millennium Bug (1999-2000)",
                "9/11 Aftermath (2001-2010)",
                "Social Media Rise (2004-2012)",
                "Cryptocurrency Era (2009-present)",
                "Quantum Computing Dawn (2019-2030)",
                "Gene Therapy Revolution (2020-2035)",
                "Mars Colonization Attempts (2025-2040)",
                "Artificial General Intelligence (2028-2045)",
                "Climate Refugee Crisis (2030-2050)",
            ],
        },
        "protagonist_elements": {
            "archetypes": [
                "Reluctant Investigator",
                "Traumatized Survivor",
                "Skeptical Academic",
                "Protective Parent",
                "Guilty Accomplice",
                "Tormented Artist",
                "Curious Journalist",
                "Desperate Patient",
                "Isolated Caretaker",
                "Haunted Detective",
                "Grieving Spouse",
                "Paranormal Researcher",
                "Reformed Criminal",
                "Medical Professional",
                "Religious Figure",
                "Existential Philosopher",
                "Quantum Physicist",
                "Genetic Engineer",
                "AI Researcher",
                "Memory Specialist",
                "Consciousness Explorer",
                "Time Traveler",
                "Dimension Walker",
                "Reality Architect",
                "Truth Seeker",
                "Knowledge Guardian",
                "Secret Keeper",
                "Fate Challenger",
                "Destiny Manipulator",
                "Probability Calculator",
                "Pattern Recognizer",
                "System Analyst",
                "Network Navigator",
                "Code Breaker",
                "Signal Interceptor",
                "Frequency Tuner",
                "Wavelength Surfer",
                "Information Gatherer",
                "Data Archaeologist",
                "Digital Detective",
                "Virtual Explorer",
                "Cyber Investigator",
                "Neural Hacker",
                "Brain Mapper",
                "Mind Reader",
                "Thought Decoder",
                "Dream Interpreter",
                "Nightmare Analyst",
                "Fear Cataloguer",
                "Terror Taxonomist",
            ],
            "backgrounds": [
                "Psychology Professor",
                "Crime Scene Investigator",
                "Documentary Filmmaker",
                "Social Worker",
                "Paramedic/EMT",
                "Librarian/Archivist",
                "Security Guard",
                "Nurse/Doctor",
                "Therapist/Counselor",
                "Museum Curator",
                "Fire Fighter",
                "Park Ranger",
                "Teacher/Principal",
                "Antique Dealer",
                "Real Estate Agent",
                "Quantum Physicist",
                "Genetic Counselor",
                "AI Ethicist",
                "Neuroscientist",
                "Archaeologist",
                "Cryptographer",
                "Linguist",
                "Anthropologist",
                "Philosopher",
                "Mathematician",
                "Computer Programmer",
                "Systems Analyst",
                "Network Security Expert",
                "Data Scientist",
                "Research Scientist",
                "Medical Examiner",
                "Forensic Psychologist",
                "Criminal Profiler",
                "Intelligence Analyst",
                "Diplomatic Attaché",
                "War Correspondent",
                "Foreign Correspondent",
                "Investigative Reporter",
                "Book Editor",
                "Literary Critic",
                "Art Historian",
                "Music Theorist",
                "Film Critic",
                "Cultural Anthropologist",
                "Religious Studies Scholar",
                "Comparative Literature Professor",
                "Philosophy Department Head",
                "Ethics Committee Chair",
                "Research Ethics Board Member",
                "Human Rights Investigator",
            ],
            "psychological_traits": [
                "Suffers from PTSD",
                "Has psychic sensitivity",
                "Struggles with addiction",
                "Battles severe anxiety",
                "Haunted by past mistakes",
                "Possesses eidetic memory",
                "Experiences hallucinations",
                "Has survivor's guilt",
                "Suffers from insomnia",
                "Prone to panic attacks",
                "Has repressed memories",
                "Struggles with depression",
                "Experiences prophetic dreams",
                "Has obsessive tendencies",
                "Battles paranoia",
                "Exhibits synesthesia",
                "Shows hypersensitivity",
                "Demonstrates empathic abilities",
                "Displays savant syndrome",
                "Manifests dissociation",
                "Experiences déjà vu frequently",
                "Has temporal perception disorder",
                "Shows pattern recognition genius",
                "Exhibits mathematical intuition",
                "Demonstrates linguistic savant abilities",
                "Possesses perfect pitch",
                "Shows chromesthesia",
                "Exhibits mirror-touch synesthesia",
                "Has lexical-gustatory synesthesia",
                "Demonstrates grapheme-color synesthesia",
                "Experiences time-space synesthesia",
                "Shows number-form synesthesia",
                "Exhibits kinesthetic synesthesia",
                "Has auditory-tactile synesthesia",
                "Demonstrates sequence-space synesthesia",
                "Possesses calendar synesthesia",
                "Shows ordinal linguistic personification",
                "Exhibits misophonia",
                "Has hyperacusis",
                "Demonstrates prosopagnosia",
                "Shows aphantasia",
                "Exhibits hyperthymesia",
                "Has highly superior autobiographical memory",
                "Demonstrates selective attention disorder",
                "Exhibits attention deficit hyperactivity",
                "Shows autism spectrum characteristics",
                "Exhibits sensory processing sensitivity",
                "Has emotional hypersensitivity",
                "Demonstrates cognitive rigidity",
                "Shows executive function deficits",
            ],
            "fatal_flaws": [
                "Overwhelming curiosity",
                "Inability to leave well enough alone",
                "Desperate need for closure",
                "Protective instinct overrides logic",
                "Arrogance/Overconfidence",
                "Inability to trust others",
                "Self-destructive tendencies",
                "Guilt-driven decisions",
                "Refuses to accept supernatural explanations",
                "Takes unnecessary risks for others",
                "Cannot abandon those in need",
                "Obsessed with proving theories",
                "Haunted by need for justice",
                "Compulsive need to document everything",
                "Cannot resist a mystery",
                "Perfectionist paralysis",
                "Analysis paralysis",
                "Information addiction",
                "Truth obsession",
                "Knowledge compulsion",
                "Pattern recognition addiction",
                "System optimization obsession",
                "Control freak tendencies",
                "Micromanagement compulsion",
                "Detail fixation disorder",
                "Completion compulsion",
                "Closure addiction",
                "Resolution obsession",
                "Answer-seeking compulsion",
                "Question-asking addiction",
                "Doubt proliferation tendency",
                "Skepticism extremism",
                "Cynicism addiction",
                "Pessimism compulsion",
                "Nihilism attraction",
                "Existential questioning obsession",
                "Meaning-seeking compulsion",
                "Purpose-finding addiction",
                "Significance-seeking disorder",
                "Importance-claiming tendency",
                "Recognition-seeking compulsion",
                "Validation addiction",
                "Approval-seeking disorder",
                "Acceptance-craving tendency",
                "Belonging-seeking compulsion",
                "Connection-making obsession",
                "Relationship-building compulsion",
                "Network-expanding addiction",
                "Influence-seeking disorder",
                "Power-accumulating tendency",
            ],
        },
    }

    # 继续添加其他部分...
    return config


# 简化版，只创建开头部分
if __name__ == "__main__":
    config = create_extended_config()

    # 保存到文件
    output_file = "config_extended_partial.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=4, ensure_ascii=False)

    print(f"已创建扩展配置文件的前半部分：{output_file}")
    print("正在准备创建完整版本...")
